
"""add_comments_table

Revision ID: 0098758a1910
Revises: ae4b024daf2b
Create Date: 2025-11-28 17:25:22.164445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0098758a1910'
down_revision = 'ae4b024daf2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
