
"""add_data_catalog_tables

Revision ID: 2270853bae17
Revises: da147ff8e661
Create Date: 2025-12-08 01:10:27.183221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2270853bae17'
down_revision = 'da147ff8e661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_name', sa.String(length=100), nullable=True),
    sa.Column('database_name', sa.String(length=100), nullable=True),
    sa.Column('full_path', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_tables_domain'), 'data_tables', ['domain'], unique=False)
    op.create_index(op.f('ix_data_tables_id'), 'data_tables', ['id'], unique=False)
    op.create_index(op.f('ix_data_tables_name'), 'data_tables', ['name'], unique=False)
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_hash', sa.String(length=64), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('concept_type', sa.String(length=50), nullable=True),
    sa.Column('data_table_id', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['data_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_history_concept_hash'), 'approval_history', ['concept_hash'], unique=False)
    op.create_index(op.f('ix_approval_history_data_table_id'), 'approval_history', ['data_table_id'], unique=False)
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.create_table('variable_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_variable_id', sa.Integer(), nullable=False),
    sa.Column('data_table_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUGGESTED', 'SELECTED', 'PENDING_OWNER', 'APPROVED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('selected_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_validated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('matched_column', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_variable_id'], ['case_variables.id'], ),
    sa.ForeignKeyConstraint(['data_table_id'], ['data_tables.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['selected_by_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variable_matches_case_variable_id'), 'variable_matches', ['case_variable_id'], unique=False)
    op.create_index(op.f('ix_variable_matches_data_table_id'), 'variable_matches', ['data_table_id'], unique=False)
    op.create_index(op.f('ix_variable_matches_id'), 'variable_matches', ['id'], unique=False)
    op.create_index(op.f('ix_variable_matches_status'), 'variable_matches', ['status'], unique=False)
    op.add_column('case_variables', sa.Column('search_status', sa.String(), nullable=True))
    op.add_column('case_variables', sa.Column('search_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_variables', sa.Column('search_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_variables', sa.Column('selected_match_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_case_variables_search_status'), 'case_variables', ['search_status'], unique=False)
    op.create_foreign_key(None, 'case_variables', 'variable_matches', ['selected_match_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_variables', type_='foreignkey')
    op.drop_index(op.f('ix_case_variables_search_status'), table_name='case_variables')
    op.drop_column('case_variables', 'selected_match_id')
    op.drop_column('case_variables', 'search_completed_at')
    op.drop_column('case_variables', 'search_started_at')
    op.drop_column('case_variables', 'search_status')
    op.drop_index(op.f('ix_variable_matches_status'), table_name='variable_matches')
    op.drop_index(op.f('ix_variable_matches_id'), table_name='variable_matches')
    op.drop_index(op.f('ix_variable_matches_data_table_id'), table_name='variable_matches')
    op.drop_index(op.f('ix_variable_matches_case_variable_id'), table_name='variable_matches')
    op.drop_table('variable_matches')
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_data_table_id'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_concept_hash'), table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_data_tables_name'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_id'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_domain'), table_name='data_tables')
    op.drop_table('data_tables')
    # ### end Alembic commands ###
