
"""Add estimated_use_date to cases

Revision ID: b0eeb1936bdf
Revises: 0098758a1910
Create Date: 2025-12-07 21:02:18.348120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0eeb1936bdf'
down_revision = '0098758a1910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('cases', sa.Column('estimated_use_date', sa.Date(), nullable=True))
    op.drop_column('cases', 'end_date')
    op.drop_column('cases', 'start_date')
    op.drop_column('cases', 'budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('budget', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('cases', 'estimated_use_date')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
