
"""Add moderation tables

Revision ID: da147ff8e661
Revises: b0eeb1936bdf
Create Date: 2025-12-08 00:02:54.725402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da147ff8e661'
down_revision = 'b0eeb1936bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create moderation_requests FIRST (no dependencies on associations)
    op.create_table('moderation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'SIX_MONTHS', name='moderationduration'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='moderationrequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_renewal', sa.Boolean(), nullable=True),
    sa.Column('previous_association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_requests_id'), 'moderation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_requests_moderator_id'), 'moderation_requests', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_requests_status'), 'moderation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_moderation_requests_user_id'), 'moderation_requests', ['user_id'], unique=False)
    
    # Create moderation_associations SECOND (depends on requests)
    op.create_table('moderation_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='moderationassociationstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_id', sa.Integer(), nullable=True),
    sa.Column('expiration_warning_sent', sa.Boolean(), nullable=True),
    sa.Column('expiration_notification_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_associations_id'), 'moderation_associations', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_associations_moderator_id'), 'moderation_associations', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_associations_status'), 'moderation_associations', ['status'], unique=False)
    op.create_index(op.f('ix_moderation_associations_user_id'), 'moderation_associations', ['user_id'], unique=False)
    
    # Add the circular FK after both tables exist
    op.create_foreign_key('fk_requests_previous_association', 'moderation_requests', 'moderation_associations', ['previous_association_id'], ['id'])
    
    # Create notifications table
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MATCH_SUGGESTED', 'OWNER_REVIEW_REQUEST', 'OWNER_APPROVED', 'OWNER_REJECTED', 'REQUESTER_REVIEW_REQUEST', 'MATCH_CONFIRMED', 'MATCH_DISCARDED', 'SYNC_COMPLETED', 'SYSTEM_ALERT', 'MODERATION_REQUEST', 'MODERATION_APPROVED', 'MODERATION_REJECTED', 'MODERATION_CANCELLED', 'MODERATION_STARTED', 'MODERATION_EXPIRING', 'MODERATION_EXPIRED', 'MODERATION_REVOKED', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['case_variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_moderation_requests_user_id'), table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_status'), table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_moderator_id'), table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_id'), table_name='moderation_requests')
    op.drop_table('moderation_requests')
    op.drop_index(op.f('ix_moderation_associations_user_id'), table_name='moderation_associations')
    op.drop_index(op.f('ix_moderation_associations_status'), table_name='moderation_associations')
    op.drop_index(op.f('ix_moderation_associations_moderator_id'), table_name='moderation_associations')
    op.drop_index(op.f('ix_moderation_associations_id'), table_name='moderation_associations')
    op.drop_table('moderation_associations')
    # ### end Alembic commands ###
