
"""Add CaseDocument

Revision ID: ef0d52b2d047
Revises: a1b2c3d4e5f6
Create Date: 2025-11-27 21:14:29.846200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0d52b2d047'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_id'), 'case_documents', ['id'], unique=False)
    op.drop_index(op.f('idx_case_vars_gin'), table_name='case_variables', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_case_vars_gin'), 'case_variables', ['variable_value'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_case_documents_id'), table_name='case_documents')
    op.drop_table('case_documents')
    # ### end Alembic commands ###
